// src/components/layout/Header.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { useRouter } from 'vue-router';
import { useUIStore } from '@/stores/ui';
import { useAuthStore } from '@/stores/auth';
import RestaurantSwitcher from '@/components/ui/RestaurantSwitcher.vue';
import {
  Menu,
  Globe,
  Bell,
  Search,
  Sparkles,
  LogOut,
  ChevronDown
} from 'lucide-vue-next';

const router = useRouter();
const uiStore = useUIStore();
const authStore = useAuthStore();

const searchQuery = ref('');
const searchRoutes = [
  { keywords: 'dashboard الرئيسية', path: '/dashboard' }, { keywords: 'employees الموظفين', path: '/employees' },
  { keywords: 'attendance الحضور', path: '/attendance' }, { keywords: 'leave الإجازات', path: '/leave-requests' },
  { keywords: 'orders الطلبات المطبخ', path: '/orders' }, { keywords: 'inventory المخزون', path: '/inventory' },
  { keywords: 'menu القائمة', path: '/menu' }, { keywords: 'reports التقارير', path: '/reports' },
  { keywords: 'alerts التنبيهات', path: '/alerts' }, { keywords: 'schedule الجدولة', path: '/scheduling' },
];
function submitSearch() {
  const q = searchQuery.value.trim().toLowerCase();
  if (!q) return;
  const found = searchRoutes.find(r => r.keywords.includes(q));
  if (found) { router.push(found.path); searchQuery.value = ''; }
}
const userDropdownOpen = ref(false);
const dropdownRef = ref<HTMLElement | null>(null);

function toggleLanguage() {
  uiStore.toggleLanguage();
}

function openAlerts() {
  router.push('/alerts');
}

async function handleLogout() {
  userDropdownOpen.value = false;
  await authStore.logout();
  await router.replace('/login');
}

function handleClickOutside(event: MouseEvent) {
  if (dropdownRef.value && !dropdownRef.value.contains(event.target as Node)) {
    userDropdownOpen.value = false;
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside);
});

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside);
});
</script>

<template>
  <header class="sticky top-0 z-20 h-[76px] sm:h-[80px] bg-[#0b131a] text-slate-100 border-b border-[#162534] px-3 sm:px-6 flex items-center justify-between gap-3 shadow-md select-none transition-all">
    <!-- Left: Mobile Menu Trigger -->
    <div class="flex items-center gap-2 sm:gap-3 shrink-0">
      <!-- Mobile Navigation Hamburger -->
      <button
        type="button"
        class="lg:hidden p-2 sm:p-2.5 rounded-xl bg-[#12202f] hover:bg-[#1a2d40] border border-[#1e344d] hover:border-[#4edee3]/40 text-slate-200 hover:text-white transition-all cursor-pointer shadow-xs active:scale-95"
        :aria-label="$t('nav.dashboard')"
        @click="uiStore.setMobileMenuOpen(true)"
      >
        <Menu class="w-5 h-5 text-slate-200" />
      </button>
    </div>

    <!-- Center: Desktop Search Input -->
    <div class="hidden md:flex items-center flex-1 max-w-sm lg:max-w-md mx-2 lg:mx-4">
      <div class="relative w-full">
        <Search class="absolute start-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
        <input
          v-model="searchQuery"
          type="search"
          @keydown.enter.prevent="submitSearch"
          :placeholder="$t('common.search')"
          class="w-full bg-[#12202f] border border-[#1e344d] hover:border-slate-600 focus:border-[#4edee3] focus:ring-2 focus:ring-[#4edee3]/20 rounded-xl py-2 ps-10 pe-10 text-xs text-white placeholder-slate-400 transition-all outline-none"
        />
        <kbd class="absolute end-3 top-1/2 -translate-y-1/2 px-1.5 py-0.5 text-[10px] font-mono text-slate-400 bg-slate-800/80 rounded border border-slate-700">↵</kbd>
      </div>
    </div>

    <!-- Active tenant: the same selector used by mobile navigation. -->
    <RestaurantSwitcher class="hidden lg:block max-w-[230px]" />

    <!-- Right: Controls & User Profile -->
    <div class="flex items-center gap-2 sm:gap-2.5 shrink-0">
      <!-- AI Intelligence Pill (Wide screens only) -->
      <router-link
        to="/ai-intelligence"
        class="hidden xl:inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-[#4edee3]/15 text-[#4edee3] border border-[#4edee3]/30 hover:bg-[#4edee3]/25 text-xs font-semibold transition-colors"
      >
        <Sparkles class="w-3.5 h-3.5" />
        <span>RestoraAI</span>
      </router-link>

      <!-- Single Primary Language Switcher -->
      <button
        type="button"
        class="inline-flex items-center gap-2 px-3 py-2 rounded-xl bg-[#12202f] hover:bg-[#1a2d40] border border-[#1e344d] hover:border-[#4edee3]/50 text-xs font-bold text-white transition-all cursor-pointer shadow-xs active:scale-95"
        :title="uiStore.language === 'ar' ? 'Switch to English' : 'التحويل للعربية'"
        @click="toggleLanguage"
      >
        <Globe class="w-4 h-4 text-[#4edee3]" />
        <span class="font-mono text-xs uppercase tracking-wide text-white">{{ uiStore.language === 'ar' ? 'EN' : 'عربي' }}</span>
      </button>

      <!-- Incident Notifications Bell -->
      <button
        type="button"
        class="relative p-2.5 rounded-xl bg-[#12202f] hover:bg-[#1a2d40] border border-[#1e344d] hover:border-[#4edee3]/50 text-slate-200 hover:text-white transition-all shadow-xs cursor-pointer active:scale-95"
        :title="$t('common.notifications')"
        @click="openAlerts"
      >
        <Bell class="w-4 h-4 text-slate-200" />
        <span class="absolute top-2 end-2 w-2 h-2 rounded-full bg-rose-500 ring-2 ring-[#0b131a]" />
      </button>

      <!-- Vertical subtle separator on medium and up -->
      <div class="h-8 w-px bg-[#1e344d] hidden sm:block mx-0.5"></div>

      <!-- User Profile (Showing Name & Role on Large Screens) -->
      <div ref="dropdownRef" class="relative">
        <button
          type="button"
          class="flex items-center gap-2.5 p-1 sm:px-2.5 sm:py-1.5 rounded-xl bg-[#12202f]/70 hover:bg-[#12202f] border border-[#1e344d] hover:border-[#4edee3]/40 transition-all cursor-pointer focus:outline-none group shadow-xs"
          @click="userDropdownOpen = !userDropdownOpen"
        >
          <!-- Avatar with online badge -->
          <div class="relative shrink-0">
            <img
              :src="authStore.currentUser?.avatar_url || 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80'"
              alt="Avatar"
              class="w-9 h-9 sm:w-10 sm:h-10 rounded-xl object-cover ring-2 ring-[#1e344d] group-hover:ring-[#4edee3]/60 transition-all shadow-xs"
            />
            <span class="absolute -bottom-0.5 -end-0.5 w-2.5 h-2.5 rounded-full bg-emerald-500 ring-2 ring-[#0b131a]" />
          </div>

          <!-- Name & Role (Visible on md/lg and larger screens) -->
          <div class="hidden md:flex flex-col text-start min-w-0 max-w-[130px] lg:max-w-[170px] xl:max-w-[200px]">
            <span class="text-xs font-bold text-white truncate leading-tight group-hover:text-[#4edee3] transition-colors">
              {{ authStore.currentUser?.name[uiStore.language] }}
            </span>
            <span class="text-[10px] font-semibold text-[#4edee3] truncate leading-tight mt-0.5">
              {{ $t('common.userRole') }}
            </span>
          </div>

          <ChevronDown
            class="w-3.5 h-3.5 text-slate-400 group-hover:text-white transition-transform duration-200 shrink-0 ms-0.5"
            :class="{ 'rotate-180': userDropdownOpen }"
          />
        </button>

        <!-- Compact User Menu (Clean style with dark border) -->
        <div
          v-if="userDropdownOpen"
          class="absolute top-full mt-2 end-0 w-64 bg-white rounded-2xl border-2 border-slate-900 shadow-[0_12px_40px_rgba(0,0,0,0.22)] z-50 p-2 animate-in fade-in zoom-in-95 duration-100 text-slate-800"
        >
          <!-- User Info Header -->
          <div class="px-3.5 py-3 bg-slate-50 border border-slate-200/90 rounded-xl mb-1.5 flex items-center gap-3">
            <img
              :src="authStore.currentUser?.avatar_url || 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80'"
              alt="Avatar"
              class="w-10 h-10 rounded-xl object-cover border border-slate-200 shrink-0"
            />
            <div class="flex-1 min-w-0">
              <p class="text-xs font-bold text-slate-900 truncate">
                {{ authStore.currentUser?.name[uiStore.language] }}
              </p>
              <p class="text-[11px] text-[#0f766e] font-semibold truncate mt-0.5">
                {{ $t('common.userRole') }}
              </p>
              <p class="text-[10px] text-slate-400 font-mono truncate mt-0.5">
                {{ authStore.currentUser?.email || 'sara@restoraintel.sa' }}
              </p>
            </div>
          </div>

          <!-- Actions -->
          <div class="space-y-0.5">
            <button
              type="button"
              class="w-full flex items-center gap-2.5 px-3 py-2 rounded-xl text-xs font-semibold text-rose-600 hover:bg-rose-50 hover:text-rose-700 transition-colors cursor-pointer"
              @click="handleLogout"
            >
              <LogOut class="w-4 h-4" />
              <span>{{ uiStore.language === 'ar' ? 'تسجيل الخروج' : 'Logout' }}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  </header>
</template>

// src/components/layout/Header.tsx
import React, { useState, useRef, useEffect } from 'react';
import {
  Menu,
  Bell,
  Globe,
  Store,
  ChevronDown,
  Sparkles,
  CheckCheck,
  Building2,
  Check,
  User,
  ShieldCheck,
  ExternalLink,
  MapPin,
  Flame,
} from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { PageId } from '../../types';
import { Avatar } from '../ui/Avatar';
import { translateTimestamp } from '../../utils/localization';

export const Header: React.FC = () => {
  const {
    language,
    toggleLanguage,
    t,
    currentPage,
    user,
    restaurants,
    selectedRestaurant,
    setSelectedRestaurant,
    alerts,
    markAlertAsRead,
    markAllAlertsAsRead,
    setMobileMenuOpen,
    setCurrentPage,
    showToast,
  } = useApp();

  const [branchDropdownOpen, setBranchDropdownOpen] = useState(false);
  const [notificationsOpen, setNotificationsOpen] = useState(false);
  const [profileDropdownOpen, setProfileDropdownOpen] = useState(false);

  const headerRef = useRef<HTMLElement>(null);

  // Close dropdowns when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (headerRef.current && !headerRef.current.contains(event.target as Node)) {
        setBranchDropdownOpen(false);
        setNotificationsOpen(false);
        setProfileDropdownOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const unreadAlerts = alerts.filter(a => !a.read);

  // Map currentPage to localized title
  const getPageTitle = () => {
    switch (currentPage) {
      case 'dashboard':
        return t.nav.dashboard;
      case 'employees':
        return t.nav.employees;
      case 'attendance':
        return t.nav.attendance;
      case 'scheduling':
        return t.nav.scheduling;
      case 'leave-requests':
        return t.nav.leaveRequests;
      case 'menu':
        return t.nav.menu;
      case 'orders':
        return t.nav.orders;
      case 'inventory':
        return t.nav.inventory;
      case 'alerts':
        return t.nav.alerts;
      case 'reports':
        return t.nav.reports;
      case 'ai-intelligence':
        return t.nav.aiIntelligence;
      case 'branding-preview':
        return language === 'ar' ? 'مراجعة واعتماد أصول الهوية الرقمية' : 'Brand Asset Review (Approval Gate)';
      case 'login':
        return t.nav.login;
      default:
        return 'RestoraIntel';
    }
  };

  return (
    <header
      ref={headerRef}
      className="h-16 bg-[#060E17] border-b border-[#122030] px-4 md:px-6 flex items-center justify-between z-20 shrink-0 select-none text-white shadow-md shadow-black/20"
    >
      {/* Start: Mobile Toggle & Breadcrumb / Location Badge */}
      <div className="flex items-center gap-3 min-w-0">
        <button
          onClick={() => setMobileMenuOpen(true)}
          className="md:hidden p-2 rounded-xl text-slate-300 hover:text-white hover:bg-[#0E2033] cursor-pointer transition-colors"
          aria-label="Open navigation menu"
        >
          <Menu className="w-5 h-5" />
        </button>

        {/* Small Brand Icon on mobile */}
        <div className="md:hidden flex items-center gap-2 shrink-0">
          <img
            src="/logo-mark.png"
            alt="RestoraIntel"
            onError={(e) => {
              (e.currentTarget as HTMLImageElement).src = '/logo.png';
            }}
            className="w-8 h-8 object-contain drop-shadow-[0_2px_8px_rgba(78,222,227,0.3)]"
          />
        </div>

        {/* Breadcrumb Area with Wadi Al-Dawasir indicator */}
        <div className="flex items-center gap-2 text-xs md:text-sm font-semibold truncate">
          <div className="hidden sm:flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-[#0C1A2B] border border-[#162C42] text-[11px] font-mono text-[#4edee3]">
            <span className="w-1.5 h-1.5 rounded-full bg-[#4edee3] animate-pulse" />
            <span>{selectedRestaurant.code}</span>
          </div>

          <span className="text-slate-600 hidden sm:inline">/</span>

          <h1 className="text-white font-bold tracking-tight text-sm sm:text-base truncate">
            {getPageTitle()}
          </h1>
        </div>
      </div>

      {/* End: Controls, Branch Switcher, AI Status, Notifications, Language, Manager Profile */}
      <div className="flex items-center gap-2 sm:gap-2.5 md:gap-3">
        {/* RestoraAI Pulse Status Pill */}
        <button
          onClick={() => {
            setCurrentPage('ai-intelligence');
            showToast(
              language === 'ar'
                ? 'تم الانتقال لمركز الذكاء الاصطناعي - مصفوفة وادي الدواسر نشطة'
                : 'Switched to RestoraAI Intelligence Core - Wadi Al-Dawasir Matrix active'
            );
          }}
          className="hidden lg:flex items-center gap-2 px-3 py-1.5 rounded-full bg-[#140C24] border border-[#8B5CF6]/40 text-[#DDD6FE] text-xs font-semibold cursor-pointer hover:bg-[#1E1335] hover:border-[#8B5CF6]/70 transition-all shadow-xs"
          title="RestoraAI Neural Engine Active & Synchronized"
        >
          <span className="relative flex h-2 w-2">
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-[#8B5CF6] opacity-75" />
            <span className="relative inline-flex rounded-full h-2 w-2 bg-[#A78BFA]" />
          </span>
          <Sparkles className="w-3.5 h-3.5 text-[#C4B5FD]" />
          <span className="tracking-wide">RestoraAI Live</span>
        </button>

        {/* Branch Context Selector Dropdown */}
        <div className="relative">
          <button
            onClick={() => {
              setBranchDropdownOpen(!branchDropdownOpen);
              setNotificationsOpen(false);
              setProfileDropdownOpen(false);
            }}
            className="flex items-center gap-2 px-2.5 sm:px-3 py-1.5 rounded-xl border border-[#162D46] bg-[#0A1726] hover:bg-[#0E2034] hover:border-[#4edee3]/50 text-xs font-semibold text-slate-200 transition-all cursor-pointer shadow-xs"
            aria-label="Select Restaurant Branch"
          >
            <div className="w-5 h-5 rounded-lg bg-[#4edee3]/15 text-[#4edee3] flex items-center justify-center shrink-0">
              <Store className="w-3 h-3" />
            </div>
            <span className="hidden sm:inline max-w-[130px] md:max-w-[160px] truncate text-slate-100">
              {selectedRestaurant.name[language]}
            </span>
            <span className="sm:hidden font-mono text-[11px] text-[#4edee3] font-bold">
              {selectedRestaurant.code}
            </span>
            <ChevronDown className="w-3.5 h-3.5 text-slate-400 shrink-0" />
          </button>

          {branchDropdownOpen && (
            <div className="absolute end-0 mt-2 w-80 rounded-2xl bg-[#060E17] border border-[#182F48] shadow-2xl py-2 z-50 animate-in fade-in zoom-in-95 text-slate-200">
              <div className="px-4 py-2 border-b border-[#122030] text-[10px] font-bold text-[#4edee3] uppercase tracking-wider flex items-center justify-between">
                <span>{language === 'ar' ? 'فروع السلسلة المتاحة' : 'Active Chain Branches'}</span>
                <Building2 className="w-3.5 h-3.5 text-slate-400" />
              </div>

              <div className="max-h-72 overflow-y-auto py-1 divide-y divide-[#122030]/60">
                {restaurants.map(rest => {
                  const isSelected = rest.id === selectedRestaurant.id;
                  return (
                    <button
                      key={rest.id}
                      onClick={() => {
                        setSelectedRestaurant(rest);
                        setBranchDropdownOpen(false);
                        showToast(
                          language === 'ar'
                            ? `تم تبديل سياق العمليات إلى: ${rest.name.ar}`
                            : `Switched operational context to: ${rest.name.en}`
                        );
                      }}
                      className={`w-full text-start px-4 py-3 flex items-start gap-3 text-xs transition-colors cursor-pointer ${
                        isSelected
                          ? 'bg-[#0B1E33] text-white font-bold border-s-2 border-[#4edee3]'
                          : 'text-slate-300 hover:bg-[#0A1726] hover:text-white'
                      }`}
                    >
                      <span
                        className={`w-2 h-2 rounded-full mt-1.5 shrink-0 ${
                          isSelected ? 'bg-[#4edee3] ring-2 ring-[#4edee3]/30' : 'bg-slate-600'
                        }`}
                      />
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center justify-between gap-1">
                          <p className="truncate text-xs font-semibold text-white">{rest.name[language]}</p>
                          {isSelected && <Check className="w-3.5 h-3.5 text-[#4edee3] shrink-0" />}
                        </div>
                        <p className="text-[11px] text-slate-400 font-mono mt-0.5 flex items-center gap-1.5">
                          <span className="text-[#4edee3] font-bold">{rest.code}</span>
                          <span>•</span>
                          <span>{rest.city[language]}</span>
                          <span>•</span>
                          <span>{rest.active_tables_count} {language === 'ar' ? 'طاولة' : 'tables'}</span>
                        </p>
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>
          )}
        </div>

        {/* Language Switcher Button (Instant LTR / RTL) */}
        <button
          onClick={() => {
            toggleLanguage();
            showToast(
              language === 'ar'
                ? 'Switched language to English (LTR layout)'
                : 'تم التحويل إلى اللغة العربية (تنسيق RTL)'
            );
          }}
          className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-xl border border-[#162D46] bg-[#0A1726] hover:bg-[#0E2034] hover:border-[#4edee3]/50 text-xs font-semibold text-slate-200 transition-all cursor-pointer shadow-xs"
          title={language === 'ar' ? 'Switch to English (LTR)' : 'التحويل للعربية (RTL)'}
          aria-label="Toggle language"
        >
          <Globe className="w-3.5 h-3.5 text-[#4edee3]" />
          <span className="font-mono text-[11px] font-bold">
            {language === 'ar' ? 'EN' : 'عربي'}
          </span>
        </button>

        {/* Notifications Popover */}
        <div className="relative">
          <button
            onClick={() => {
              setNotificationsOpen(!notificationsOpen);
              setBranchDropdownOpen(false);
              setProfileDropdownOpen(false);
            }}
            className="relative p-2 rounded-xl text-slate-300 hover:text-white hover:bg-[#0E2033] border border-transparent hover:border-[#162D46] transition-all cursor-pointer"
            aria-label="Incident Notifications"
          >
            <Bell className="w-4 h-4" />
            {unreadAlerts.length > 0 && (
              <span className="absolute top-1.5 end-1.5 w-2 h-2 rounded-full bg-rose-500 ring-2 ring-[#060E17]" />
            )}
          </button>

          {notificationsOpen && (
            <div className="absolute end-0 mt-2 w-80 sm:w-96 rounded-2xl bg-[#060E17] border border-[#182F48] shadow-2xl z-50 overflow-hidden animate-in fade-in text-white">
              {/* Header */}
              <div className="px-4 py-3 border-b border-[#122030] bg-[#0A1726] flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="text-xs font-bold text-white">{t.common.notifications}</span>
                  {unreadAlerts.length > 0 && (
                    <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-rose-500/20 text-rose-300 border border-rose-500/30 font-mono">
                      {unreadAlerts.length} {language === 'ar' ? 'جديد' : 'New'}
                    </span>
                  )}
                </div>
                {unreadAlerts.length > 0 && (
                  <button
                    onClick={markAllAlertsAsRead}
                    className="text-[11px] text-[#4edee3] hover:text-[#34abb1] font-semibold flex items-center gap-1 cursor-pointer transition-colors"
                  >
                    <CheckCheck className="w-3.5 h-3.5" />
                    <span>{t.alerts.markAllRead}</span>
                  </button>
                )}
              </div>

              {/* Alert Items List */}
              <div className="max-h-80 overflow-y-auto divide-y divide-[#122030]">
                {alerts.slice(0, 5).map(alert => (
                  <div
                    key={alert.id}
                    onClick={() => {
                      markAlertAsRead(alert.id);
                      if (alert.action_link) {
                        setCurrentPage(alert.action_link as PageId);
                        setNotificationsOpen(false);
                      }
                    }}
                    className={`p-3.5 text-start hover:bg-[#0C1A2B] cursor-pointer transition-colors ${
                      !alert.read ? 'bg-[#081524]' : ''
                    }`}
                  >
                    <div className="flex items-center justify-between gap-2 mb-1">
                      <span
                        className={`text-[9px] font-bold px-1.5 py-0.5 rounded-md uppercase font-mono ${
                          alert.type === 'critical'
                            ? 'bg-rose-950/80 text-rose-300 border border-rose-800/60'
                            : alert.type === 'ai'
                            ? 'bg-purple-950/80 text-purple-300 border border-purple-800/60'
                            : 'bg-amber-950/80 text-amber-300 border border-amber-800/60'
                        }`}
                      >
                        {alert.type === 'critical'
                          ? language === 'ar' ? 'حرج' : 'CRITICAL'
                          : alert.type === 'ai'
                          ? language === 'ar' ? 'ذكاء اصطناعي' : 'AI SIGNAL'
                          : language === 'ar' ? 'تشغيلي' : 'OPERATIONAL'}
                      </span>
                      <span className="text-[10px] text-slate-400 font-mono">
                        {translateTimestamp(alert.timestamp, language)}
                      </span>
                    </div>
                    <p className="text-xs font-semibold text-slate-100 leading-tight">
                      {alert.title[language]}
                    </p>
                    <p className="text-[11px] text-slate-400 mt-1 line-clamp-2 leading-relaxed">
                      {alert.message[language]}
                    </p>
                  </div>
                ))}
              </div>

              {/* Footer */}
              <div className="p-2.5 border-t border-[#122030] bg-[#0A1726] text-center">
                <button
                  onClick={() => {
                    setCurrentPage('alerts');
                    setNotificationsOpen(false);
                  }}
                  className="text-xs text-[#4edee3] hover:text-[#34abb1] font-semibold cursor-pointer"
                >
                  {language === 'ar' ? 'عرض كافة التنبيهات والأحداث' : 'View All Incident Logs'}
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Manager Profile Menu */}
        <div className="relative ps-1 border-s border-[#122030]">
          <button
            onClick={() => {
              setProfileDropdownOpen(!profileDropdownOpen);
              setNotificationsOpen(false);
              setBranchDropdownOpen(false);
            }}
            className="flex items-center gap-2 p-1 rounded-xl hover:bg-[#0E2033] border border-transparent hover:border-[#162D46] transition-all cursor-pointer"
            aria-label="User Account Menu"
          >
            <Avatar src={user.avatar_url} name={user.name[language]} size="sm" status="online" />
            <div className="hidden xl:flex flex-col text-start leading-tight">
              <span className="text-xs font-bold text-slate-100">{user.name[language]}</span>
              <span className="text-[10px] text-[#4edee3] flex items-center gap-1 font-medium mt-0.5">
                <ShieldCheck className="w-2.5 h-2.5" />
                {t.common.userRole}
              </span>
            </div>
            <ChevronDown className="hidden xl:block w-3.5 h-3.5 text-slate-400" />
          </button>

          {profileDropdownOpen && (
            <div className="absolute end-0 mt-2 w-64 rounded-2xl bg-[#060E17] border border-[#182F48] shadow-2xl py-2 z-50 animate-in fade-in text-white">
              <div className="px-4 py-3 border-b border-[#122030] bg-[#0A1726]/60 flex items-center gap-3">
                <Avatar src={user.avatar_url} name={user.name[language]} size="md" status="online" />
                <div className="min-w-0">
                  <p className="text-xs font-bold text-white truncate">{user.name[language]}</p>
                  <p className="text-[11px] text-slate-400 truncate font-mono mt-0.5">{user.email}</p>
                  <div className="mt-1.5 inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-[#4edee3]/15 border border-[#34abb1]/40 text-[#4edee3] text-[10px] font-semibold">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#4edee3]" />
                    <span>{t.common.userRole}</span>
                  </div>
                </div>
              </div>

              <div className="py-1">
                <button
                  onClick={() => {
                    setCurrentPage('dashboard');
                    setProfileDropdownOpen(false);
                  }}
                  className="w-full text-start px-4 py-2.5 text-xs text-slate-300 hover:bg-[#0C1A2B] hover:text-white flex items-center gap-2.5 cursor-pointer"
                >
                  <MapPin className="w-4 h-4 text-[#4edee3]" />
                  <span>{language === 'ar' ? 'فرع وادي الدواسر الرئيسي' : 'Wadi Al-Dawasir Flagship'}</span>
                </button>

                <button
                  onClick={() => {
                    setCurrentPage('login');
                    setProfileDropdownOpen(false);
                  }}
                  className="w-full text-start px-4 py-2.5 text-xs text-slate-300 hover:bg-[#0C1A2B] hover:text-white flex items-center gap-2.5 cursor-pointer border-t border-[#122030]"
                >
                  <User className="w-4 h-4 text-slate-400" />
                  <span>{t.nav.login} / {language === 'ar' ? 'تبديل الحساب' : 'Switch Role'}</span>
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </header>
  );
};
