// src/pages/OrdersPage.tsx
import React, { useState } from 'react';
import {
  ShoppingBag,
  Clock,
  CheckCircle2,
  Bell,
  ArrowRight,
  ArrowLeft,
  Flame,
} from 'lucide-react';
import { useApp } from '../context/AppContext';
import { PageContainer } from '../components/layout/PageContainer';
import { Card, CardContent, CardFooter } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Badge } from '../components/ui/Badge';
import { Order } from '../types';
import { translateServerName, translateTableName, translateOrderNote } from '../utils/localization';

export const OrdersPage: React.FC = () => {
  const {
    t,
    language,
    direction,
    orders,
    advanceOrderStatus,
    showToast,
  } = useApp();

  type OrderStatusType = Order['status'];

  const columns: { status: OrderStatusType; label: string; icon: React.ReactNode; color: string }[] = [
    {
      status: 'new',
      label: t.orders.new,
      icon: <Bell className="w-4 h-4 text-sky-600" />,
      color: 'border-sky-300 bg-sky-50/20',
    },
    {
      status: 'preparing',
      label: t.orders.preparing,
      icon: <Flame className="w-4 h-4 text-amber-600" />,
      color: 'border-amber-300 bg-amber-50/20',
    },
    {
      status: 'ready',
      label: t.orders.ready,
      icon: <CheckCircle2 className="w-4 h-4 text-emerald-600" />,
      color: 'border-emerald-300 bg-emerald-50/20',
    },
    {
      status: 'delivered',
      label: t.orders.delivered,
      icon: <ShoppingBag className="w-4 h-4 text-slate-500" />,
      color: 'border-slate-300 bg-slate-50/20',
    },
  ];

  const getNextStatusButtonLabel = (curr: OrderStatusType) => {
    switch (curr) {
      case 'new':
        return t.orders.markPreparing;
      case 'preparing':
        return t.orders.markReady;
      case 'ready':
        return t.orders.markDelivered;
      default:
        return '';
    }
  };

  return (
    <PageContainer
      title={t.orders.title}
      subtitle={t.orders.subtitle}
      badge={
        <Badge variant="info" size="sm" dot>
          {language === 'ar' ? 'مزامنة شاشات المطبخ الفورية' : 'KDS Real-Time Synchronizer'}
        </Badge>
      }
    >
      {/* 4-Column KDS Board */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 items-start">
        {columns.map(col => {
          const colOrders = orders.filter(o => o.status === col.status);
          return (
            <div key={col.status} className="space-y-3">
              {/* Column Header */}
              <div className="p-3 rounded-xl bg-white border border-slate-200 flex items-center justify-between shadow-xs">
                <div className="flex items-center gap-2">
                  {col.icon}
                  <span className="font-bold text-xs text-slate-900">{col.label}</span>
                </div>
                <span className="text-xs font-black px-2 py-0.5 rounded-full bg-slate-100 text-slate-700">
                  {colOrders.length}
                </span>
              </div>

              {/* Tickets Stack */}
              <div className="space-y-3 min-h-[300px]">
                {colOrders.map(order => {
                  const hasNext = order.status !== 'delivered' && order.status !== 'cancelled';
                  const isDelayed = order.elapsed_minutes > 15 && order.status !== 'delivered';

                  return (
                    <Card
                      key={order.id}
                      className={`transition-all shadow-xs ${
                        isDelayed ? 'border-rose-400 bg-rose-50/20' : 'hover:border-slate-300'
                      }`}
                    >
                      {/* Ticket Header */}
                      <div className="p-3.5 border-b border-slate-100 flex items-center justify-between">
                        <div>
                          <span className="font-mono font-black text-sm text-slate-900 block">
                            #{order.order_number}
                          </span>
                          <span className="text-[11px] font-semibold text-slate-500">
                            {translateTableName(order.table_number, language) ||
                              (order.order_type === 'takeaway'
                                ? language === 'ar' ? 'طلب خارجي' : 'Takeaway'
                                : order.order_type === 'delivery'
                                ? language === 'ar' ? 'توصيل' : 'Delivery'
                                : order.order_type)}{' '}
                            • {translateServerName(order.server_name, language)}
                          </span>
                        </div>

                        {/* Elapsed Timer */}
                        <div
                          className={`flex items-center gap-1 text-xs font-mono font-bold px-2 py-1 rounded-lg ${
                            isDelayed
                              ? 'bg-rose-100 text-rose-800 animate-pulse'
                              : 'bg-slate-100 text-slate-700'
                          }`}
                        >
                          <Clock className="w-3.5 h-3.5" />
                          <span>{order.elapsed_minutes}m</span>
                        </div>
                      </div>

                      {/* Items List */}
                      <CardContent className="p-3.5 space-y-2">
                        {order.items.map((item, idx) => (
                          <div key={idx} className="flex items-start justify-between text-xs">
                            <div className="flex items-center gap-2">
                              <span className="font-bold text-[#2c777c] font-mono">
                                {item.quantity}x
                              </span>
                              <span className="font-semibold text-slate-800">
                                {item.name[language]}
                              </span>
                            </div>
                            {item.notes && (
                              <span className="text-[10px] text-amber-700 font-mono bg-amber-50 px-1 rounded">
                                {translateOrderNote(item.notes, language)}
                              </span>
                            )}
                          </div>
                        ))}
                      </CardContent>

                      {/* Ticket Footer Action */}
                      {hasNext && (
                        <CardFooter className="p-2.5 bg-slate-50 border-t border-slate-100">
                          <Button
                            variant={order.status === 'ready' ? 'primary' : 'outline'}
                            size="sm"
                            className="w-full text-xs font-bold"
                            onClick={() => {
                              advanceOrderStatus(order.id);
                              showToast(
                                language === 'ar'
                                  ? `تم تحديث الطلب #${order.order_number} (${getNextStatusButtonLabel(order.status)})`
                                  : `Advanced order #${order.order_number} to next KDS stage`
                              );
                            }}
                            icon={direction === 'rtl' ? <ArrowLeft className="w-3.5 h-3.5" /> : <ArrowRight className="w-3.5 h-3.5" />}
                            iconPosition="end"
                          >
                            {getNextStatusButtonLabel(order.status)}
                          </Button>
                        </CardFooter>
                      )}
                    </Card>
                  );
                })}

                {colOrders.length === 0 && (
                  <div className="h-32 rounded-xl border border-dashed border-slate-200 flex items-center justify-center text-xs text-slate-400">
                    {language === 'ar' ? 'لا توجد تذاكر في هذه المرحلة' : 'No tickets in this stage'}
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </PageContainer>
  );
};

// src/pages/OrdersPage.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useUIStore } from '@/stores/ui';
import { useAuthStore } from '@/stores/auth';
import { orderService } from '@/services/orderService';
import type { Order } from '@/types/domain';
import { ChefHat, Clock, ArrowLeft, ArrowRight, CheckCircle2 } from 'lucide-vue-next';
const ui = useUIStore(); const auth = useAuthStore();
const orders = ref<Order[]>([]); const busy = ref<string | null>(null);
const loading = ref(false); const error = ref(''); let generation = 0;
const canManage = computed(() => auth.can('restaurant.orders.manage'));
const columns = [
  {status:'new',ar:'جديد',en:'New',next:'preparing',nextAr:'بدء التجهيز',nextEn:'Start preparing',color:'border-sky-300 bg-sky-50/50'},
  {status:'preparing',ar:'قيد الإعداد',en:'Preparing',next:'ready',nextAr:'جاهز',nextEn:'Mark ready',color:'border-amber-300 bg-amber-50/50'},
  {status:'ready',ar:'جاهز',en:'Ready',next:'delivered',nextAr:'تسليم تجريبي',nextEn:'Mark delivered',color:'border-emerald-300 bg-emerald-50/50'},
  {status:'delivered',ar:'تم التسليم',en:'Delivered',next:'',nextAr:'',nextEn:'',color:'border-slate-200 bg-slate-50'}
] as const;
const currency = computed(() => auth.currentRestaurant?.currency ?? 'SAR');
function formatMoney(amount:number) { return new Intl.NumberFormat(ui.language === 'ar' ? 'ar-SA' : 'en-US',{style:'currency',currency:currency.value}).format(amount); }
async function load(id: string | undefined) {
  const stamp = ++generation; orders.value=[];error.value='';
  if(!id){loading.value=false;return;}loading.value=true;
  try { const records=await orderService.getOrders(id); if(stamp===generation)orders.value=records; }
  catch(e){if(stamp===generation)error.value=e instanceof Error?e.message:'Unable to load orders.';}
  finally{if(stamp===generation)loading.value=false;}
}
watch(() => auth.currentRestaurant?.id,load,{immediate:true});
async function nextStatus(order:Order, next:Order['status']) {
  const restaurantId=auth.currentRestaurant?.id;
  if(!restaurantId || busy.value || !canManage.value)return;
  busy.value=order.id;error.value='';
  try {const updated=await orderService.updateOrderStatus(restaurantId,order.id,next);orders.value=orders.value.map(o=>o.id===updated.id?updated:o);}
  catch(e){error.value=e instanceof Error?e.message:'Unable to update order.';}
  finally{busy.value=null;}
}
async function toggleItem(order:Order,itemId:string|undefined) {
  const id=auth.currentRestaurant?.id; if(!id||!itemId||busy.value||!canManage.value)return;
  busy.value=order.id;error.value='';
  try{const updated=await orderService.toggleItemPrepared(id,order.id,itemId);orders.value=orders.value.map(o=>o.id===updated.id?updated:o);}
  catch(e){error.value=e instanceof Error?e.message:'Unable to update item.';}
  finally{busy.value=null;}
}
</script>

<template>
  <div class="space-y-5">
    <header class="border-b border-slate-200 pb-4"><h1 class="text-2xl font-bold text-slate-900 flex items-center gap-2"><ChefHat class="w-6 h-6 text-teal-700"/>{{ ui.language === 'ar'?'شاشة المطبخ التجريبية':'Demo Kitchen Display (KDS)' }}</h1>
      <p class="text-sm text-slate-500 mt-1">{{ ui.language === 'ar'?'تذاكر تاريخية ومحاكاة مراحل الإعداد؛ لا اتصال فعلي بالمطبخ.':'Historical sample tickets with local stage transitions; no live kitchen connectivity.' }}</p></header>
    <p v-if="error" role="alert" class="text-sm text-rose-700 bg-rose-50 border border-rose-200 p-3 rounded-xl">{{ error }}</p>
    <p v-if="loading" class="p-10 bg-white rounded-2xl text-center text-slate-500">{{ ui.language==='ar'?'تحميل التذاكر…':'Loading tickets…' }}</p>
    <div v-else class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4 items-start">
      <section v-for="col in columns" :key="col.status" :class="['rounded-2xl border min-h-52 p-3 space-y-3',col.color]">
        <header class="flex justify-between items-center p-1"><h2 class="text-sm font-bold text-slate-900">{{ col[ui.language] }}</h2><span class="text-xs font-bold rounded-full px-2 py-1 bg-white/80 text-slate-700">{{ orders.filter(o=>o.status===col.status).length }}</span></header>
        <article v-for="order in orders.filter(o=>o.status===col.status)" :key="order.id" class="bg-white border border-slate-200 shadow-sm rounded-xl p-3 space-y-3">
          <div class="flex justify-between items-start gap-2"><div><p dir="ltr" class="font-mono text-sm font-bold text-slate-900">{{ order.order_number }}</p><p class="text-[11px] text-slate-500 mt-1">{{ order.order_type }} · {{ order.table_number||'—' }}</p></div><span v-if="order.priority!=='normal'" class="bg-rose-50 text-rose-700 px-2 py-1 rounded text-xs font-semibold">{{ order.priority }}</span></div>
          <ul class="divide-y divide-slate-100"><li v-for="(item,i) in order.items" :key="item.id||i" class="py-2 space-y-1"><button type="button" :disabled="!canManage||!!busy||!item.id||order.status==='delivered'" :aria-pressed="item.is_prepared" class="flex items-start gap-2 text-start w-full text-xs disabled:cursor-default" @click="toggleItem(order,item.id)"><CheckCircle2 :class="['w-4 h-4 shrink-0',item.is_prepared?'text-emerald-600':'text-slate-300']"/><span :class="item.is_prepared?'line-through text-slate-400':'font-semibold text-slate-800'">{{ item.quantity }} × {{ item.name[ui.language] }}</span></button><p v-if="item.notes" class="text-[10px] bg-amber-50 text-amber-800 rounded p-1.5">{{ item.notes }}</p></li></ul>
          <div class="border-t border-slate-100 pt-2 flex justify-between text-xs"><span class="text-slate-500 flex items-center gap-1"><Clock class="w-3 h-3"/>{{ order.elapsed_minutes }} min <span class="text-[10px]">{{ ui.language==='ar'?'(لقطة تجريبية)':'(snapshot)' }}</span></span><strong>{{ formatMoney(order.total) }}</strong></div>
          <button v-if="col.next&&canManage" type="button" :disabled="!!busy" class="w-full p-2 rounded-lg bg-teal-700 text-white text-xs font-semibold disabled:opacity-50 flex items-center justify-center gap-1" @click="nextStatus(order,col.next as Order['status'])">{{ ui.language==='ar'?col.nextAr:col.nextEn }}<ArrowLeft v-if="ui.language==='ar'" class="w-3 h-3"/><ArrowRight v-else class="w-3 h-3"/></button>
        </article>
        <p v-if="!orders.some(o=>o.status===col.status)" class="p-7 text-center text-xs text-slate-500 border border-dashed border-slate-300 rounded-xl">{{ ui.language==='ar'?'لا توجد تذاكر':'No tickets' }}</p>
      </section>
    </div>
  </div>
</template>
