// src/components/ui/Table.vue
<script setup lang="ts" generic="T extends Record<string, any>">
import { computed } from 'vue';

export interface Column<T = any> {
  key: string;
  header?: string;
  label?: string;
  align?: 'start' | 'center' | 'end' | 'left' | 'right';
  width?: string;
  render?: (item: T) => any;
  sortable?: boolean;
}

interface Props {
  columns: Column<T>[];
  data: T[];
  keyExtractor?: (item: T, index: number) => string | number;
  isLoading?: boolean;
  emptyMessage?: string;
  emptyDescription?: string;
  striped?: boolean;
  hoverable?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  keyExtractor: undefined,
  isLoading: false,
  emptyMessage: 'لا توجد بيانات للعرض حالياً',
  emptyDescription: undefined,
  striped: true,
  hoverable: true
});

const emit = defineEmits<{
  (e: 'rowClick', item: T): void;
}>();

function getItemKey(item: T, index: number): string | number {
  if (props.keyExtractor) {
    return props.keyExtractor(item, index);
  }
  return item.id || item.uuid || item.key || index;
}

function getAlignClass(align?: 'start' | 'center' | 'end' | 'left' | 'right'): string {
  switch (align) {
    case 'center':
      return 'text-center';
    case 'end':
    case 'right':
      return 'text-end';
    case 'start':
    case 'left':
    default:
      return 'text-start';
  }
}

function handleRowClick(item: T) {
  emit('rowClick', item);
}
</script>

<template>
  <div class="w-full">
    <!-- Loading State -->
    <div
      v-if="isLoading"
      class="w-full bg-white border border-slate-200 rounded-xl overflow-hidden p-8 text-center"
    >
      <slot name="loading">
        <div class="inline-block w-8 h-8 border-3 border-[#34abb1] border-t-transparent rounded-full animate-spin mb-3" />
        <p class="text-sm text-slate-500 font-medium">جاري تحميل البيانات...</p>
      </slot>
    </div>

    <!-- Empty State -->
    <div
      v-else-if="data.length === 0"
      class="w-full bg-white border border-slate-200 rounded-xl overflow-hidden p-12 text-center"
    >
      <slot name="empty">
        <p class="text-sm text-slate-600 font-medium">{{ emptyMessage }}</p>
        <p v-if="emptyDescription" class="text-xs text-slate-400 mt-1">
          {{ emptyDescription }}
        </p>
      </slot>
    </div>

    <!-- Table Container -->
    <div
      v-else
      class="w-full overflow-x-auto rounded-xl border border-slate-200/90 bg-white shadow-xs"
    >
      <table class="w-full text-sm text-slate-800 border-collapse">
        <thead class="bg-slate-50/90 text-xs font-semibold text-slate-500 uppercase tracking-wider border-b border-slate-200">
          <tr>
            <th
              v-for="col in columns"
              :key="col.key"
              :class="[
                'py-3.5 px-4 font-semibold',
                getAlignClass(col.align),
                col.width || ''
              ]"
            >
              <slot :name="`header-${col.key}`" :column="col">
                {{ col.header || col.label || col.key }}
              </slot>
            </th>
          </tr>
        </thead>
        <tbody class="divide-y divide-slate-100">
          <tr
            v-for="(item, idx) in data"
            :key="getItemKey(item, idx)"
            :class="[
              'transition-colors',
              hoverable ? 'hover:bg-slate-50/70' : '',
              striped && idx % 2 === 1 ? 'bg-slate-50/25' : 'bg-white',
              $attrs.onRowClick ? 'cursor-pointer active:bg-slate-100/60' : ''
            ]"
            @click="handleRowClick(item)"
          >
            <td
              v-for="col in columns"
              :key="col.key"
              :class="[
                'py-3.5 px-4 align-middle',
                getAlignClass(col.align)
              ]"
            >
              <!-- Dynamic slot per column key: #cell-name or generic cell slot or col.render or direct value -->
              <slot
                :name="`cell-${col.key}`"
                :item="item"
                :value="item[col.key]"
                :index="idx"
              >
                <slot
                  name="cell"
                  :column="col"
                  :item="item"
                  :value="item[col.key]"
                  :index="idx"
                >
                  <template v-if="col.render">
                    <component :is="() => col.render!(item)" />
                  </template>
                  <template v-else>
                    {{ item[col.key] !== undefined && item[col.key] !== null ? item[col.key] : '-' }}
                  </template>
                </slot>
              </slot>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

// src/components/ui/Table.tsx
import React from 'react';

export interface Column<T> {
  key: string;
  header: string;
  render?: (item: T) => React.ReactNode;
  align?: 'start' | 'center' | 'end';
  width?: string;
}

export interface TableProps<T> {
  columns: Column<T>[];
  data: T[];
  keyExtractor: (item: T) => string;
  onRowClick?: (item: T) => void;
  emptyMessage?: string;
  isLoading?: boolean;
}

export function Table<T>({
  columns,
  data,
  keyExtractor,
  onRowClick,
  emptyMessage = 'لا توجد بيانات للعرض حالياً',
  isLoading = false,
}: TableProps<T>) {
  if (isLoading) {
    return (
      <div className="w-full bg-white border border-slate-200 rounded-xl overflow-hidden p-8 text-center">
        <div className="inline-block w-8 h-8 border-3 border-emerald-600 border-t-transparent rounded-full animate-spin mb-3" />
        <p className="text-sm text-slate-500 font-medium">جاري تحميل البيانات...</p>
      </div>
    );
  }

  if (data.length === 0) {
    return (
      <div className="w-full bg-white border border-slate-200 rounded-xl overflow-hidden p-12 text-center">
        <p className="text-sm text-slate-500 font-medium">{emptyMessage}</p>
      </div>
    );
  }

  const getAlignClass = (align?: 'start' | 'center' | 'end') => {
    if (align === 'center') return 'text-center';
    if (align === 'end') return 'text-end';
    return 'text-start';
  };

  return (
    <div className="w-full overflow-x-auto rounded-xl border border-slate-200/90 bg-white shadow-xs">
      <table className="w-full text-sm text-slate-800 border-collapse">
        <thead className="bg-slate-50/90 text-xs font-semibold text-slate-500 uppercase tracking-wider border-b border-slate-200">
          <tr>
            {columns.map(col => (
              <th
                key={col.key}
                className={`py-3.5 px-4 font-semibold ${getAlignClass(col.align)} ${
                  col.width ? col.width : ''
                }`}
              >
                {col.header}
              </th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-slate-100">
          {data.map((item, idx) => (
            <tr
              key={keyExtractor(item)}
              onClick={() => onRowClick && onRowClick(item)}
              className={`transition-colors ${
                onRowClick ? 'cursor-pointer hover:bg-slate-50/80 active:bg-slate-100/60' : 'hover:bg-slate-50/50'
              } ${idx % 2 === 1 ? 'bg-slate-50/20' : 'bg-white'}`}
            >
              {columns.map(col => (
                <td
                  key={col.key}
                  className={`py-3.5 px-4 align-middle ${getAlignClass(col.align)}`}
                >
                  {col.render ? col.render(item) : (item as any)[col.key]}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
